### ISSUE TITLE
客户追踪->客户信息 增加客户姓名字段及留言预览变更

### ISSUE THREAD

**Issue by hehe04** [hehe04/ZdtbSite#23]
客户追踪->客户信息 增加客户姓名字段 数据库中已添加此字段（customerName），
点击该客户姓名时，跳转到客户详情页面(需新增)，其中内容包括，客户信息及 当前客户留言预览，

![qq 20141218061852](https://cloud.githubusercontent.com/assets/8290445/5480099/41e3ed8e-867e-11e4-9606-2845fc67c0d9.jpg)
![qq 20141218062159](https://cloud.githubusercontent.com/assets/8290445/5480142/95dda380-867e-11e4-9c8a-22759b2f0b5e.jpg)

**Comment by jiangchun1320** [comment]
![image](https://cloud.githubusercontent.com/assets/9667694/5514118/d4863ba4-885b-11e4-90ea-5766c0c5f0b0.png) 这个是所有客户的留言页面确定补到具体的一个用户，有当个用户的可以确认到
